name: Build dfscoerce Windows Executable

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install dependencies that dfscoerce.py might need
          # Common dependencies for network tools:
          pip install impacket ldap3 dnspython

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          # Create a simple entry point script that calls your main function
          echo 'import sys; from dfscoerce import main; sys.exit(main())' > dfscoerce_launcher.py
          # Use PyInstaller to create a standalone executable
          pyinstaller --onefile --name dfscoerce_windows_amd64.exe dfscoerce_launcher.py

      - name: Create zip file
        run: |
          Compress-Archive -Path .\dist\dfscoerce_windows_amd64.exe -DestinationPath dfscoerce_windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dfscoerce-windows
          path: dfscoerce_windows.zip
